; [menu_config]
; video_size  = "1440P"   ; 720P/1080P/1440P/2160P...
; video_loop  = 1         ; 1/3/5 min
; video_codec = "h264"    ; h264/h265
; lap_setime  = 1;        ; 0:off, 1/2/3:s
; audio_enable= 1;        ; 0:off, 1:on
; osd_enable  = 1;        ; 0:off, 1:on

[video_loop]
num     = 3
current = 0
description0    = "1MIN"
value0          = 0
description1    = "3MIN"
value1          = 1
description2    = "5MIN"
value2          = 2

[video_codec]
num     = 2
current = 0
description0    = "H264"
value0          = 0
description1    = "H265"
value1          = 1

[lapse_time]
num     = 4
current = 0
description0    = "OFF"
value0          = 0
description1    = "1S"
value1          = 1
description2    = "2S"
value2          = 2
description3    = "3S"
value3          = 3

[audio_enable]
num     = 2
current = 1
description0    = "OFF"
value0          = 0
description1    = "ON"
value1          = 1

[osd_enable]
num     = 2
current = 1
description0    = "OFF"
value0          = 0
description1    = "ON"
value1          = 1

[UserData]
bBootFirst     = 0

[rec_loop]
num     = 2
current = 0
description0    = "OFF"
value0          = 0
description1    = "ON"
value1          = 1

[light_frequence]
num     = 2
current = 0
description0    = "50HZ"
value0          = 0
description1    = "60HZ"
value1          = 1

[power_off]
num     = 4
current = 2
description0    = "关闭"
value0          = 0
description1    = "3分钟"
value1          = 1
description2    = "5分钟"
value2          = 2
description3    = "10分钟"
value3          = 3

[face_det]
num     = 2
current = 1
description0    = "开启"
value0          = 0
description1    = "关闭"
value1          = 1

[face_smile]
num     = 2
current = 1
description0    = "开启"
value0          = 0
description1    = "关闭"
value1          = 1

[action_audio]
num     = 2
current = 1
description0    = "关闭"
value0          = 0
description1    = "开启"
value1          = 1

[auto_screen_off]
num     = 2
current = 0
description0    = "开启"
value0          = 0
description1    = "关闭"
value1          = 1

[photo_size]
current = 4
num     = 7
description0    = "48M(8192x6144)"
value0          = 8192
description1    = "36M(8064x4536)"
value1          = 8064
description2    = "32M(7680x4320)"
value2          = 7680
description3    = "16M(5760x3240)"
value3          = 5760
description4    = "8M(3840x2160)"
value4          = 3840
description5    = "4M(2688x1512)"
value5          = 2688
description6    = "Crop-2M(1920x1080)"
value6          = 1920


[video_size]
current = 0
num     = 5
description0    = "4K30FPS"
value0          = 3840
description1    = "2.7K30FPS"
value1          = 2688
description2    = "FHD60FPS"
value2          = 1920
description3    = "FHD30FPS"
value3          = 1920
description4    = "FHD30FPS N"
value4          = 1920

[flash_led]
current = 0
num     = 3
description0    = "关闭"
value0          = 0; 0: close, 1: open, 2: auto
description1    = "开启"
value1          = 1; 0: close, 1: open, 2: auto
description2    = "自动"
value2          = 2; 0: close, 1: open, 2: auto

[isp_effect]
current = 0
num = 23
description0    = "标准"
value0          = 0
description1    = "黑白"
value1          = 1
description2    = "胶片"
value2          = 2
description3    = "鲜艳"
value3          = 3
description4    = "绿色"
value4          = 4
description5    = "红外"
value5          = 5
description6    = "高饱和"
value6          = 6
description7    = "低饱和"
value7          = 7
description8    = "ir"
value8          = 8

[language]
current = 0
num = 13
description0    = "简体中文"
value0          = 0
description1    = "繁体中文"
value1          = 1
description2    = "Japanese"
value2          = 2
description3    = "English"
value3          = 3
description4    = "Polski"
value4          = 4
description5    = "Nederlands"
value5          = 5
description6    = "Deutsch"
value6          = 6
description7    = "Francis"
value7          = 7
description8    = "Espanol"
value8          = 8
description9    = "Italiano"
value9          = 9
description10   = "Turkce"
value10         = 10
description11   = "Pyccknn"
value11         = 11
description12   = "Portugues"
value12         = 12

; 该配置会覆盖调venc的初始配置
[photo_quality]
current = 0
num = 3
description0    = "超高画质"
value0          = 95
description1    = "高画质"
value1          = 85
description2    = "普通"
value2          = 80

[status_light]
num     = 2
current = 0
description0    = "开启"
value0          = 0
description1    = "关闭"
value1          = 1

[brightness]
num     = 7
current = 3
description0    = "等级 1"
value0          = 0
description1    = "等级 2"
value1          = 1
description2    = "等级 3"
value2          = 2
description3    = "等级 4"
value3          = 3
description4    = "等级 5"
value4          = 4
description5    = "等级 6"
value5          = 5
description6    = "等级 7"
value6          = 6
